### ISSUE TITLE
python3 -m icikt error

### ISSUE THREAD

**Issue by rmflight** [MoseleyBioinformaticsLab/icikt#4]
>Traceback (most recent call last):
>   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/rmflight/.local/share/virtualenvs/checkPythonICIKendallTau-PCeVsa1u/lib/python3.9/site-packages/icikt/__main__.py", line 20, in <module>
>     from . import icikt
>   File "/home/rmflight/.local/share/virtualenvs/checkPythonICIKendallTau-PCeVsa1u/lib/python3.9/site-packages/icikt/icikt.py", line 20, in <module>
>     from kendall_dis import _kendall_dis
> ModuleNotFoundError: No module named 'kendall_dis'
> ((checkPythonICIKendallTau) ) 
>

**Comment by hunter-moseley** [comment]
I think kendall_dis.pyx is not being compiled and put into the proper place with pip install.

**Comment by psbhatt** [comment]
dr.moseley why is that second version of the import statement better than the first?

**Comment by hunter-moseley** [comment]
Have a moment to discuss?
Will be back at computer in 5 min.
