### ISSUE TITLE
no examples of running with imported package

### ISSUE THREAD

**Issue by rmflight** [MoseleyBioinformaticsLab/icikt#5]
I don't see any documentation of running things after importing the package in a python shell, but surely this is possible?

I tried following the test.py, but that seems to currently fail.

**Comment by psbhatt** [comment]
Had forgotten to update test.py for sometime, working on that now

**Comment by rmflight** [comment]
I think you need an example useage on the README.rst, and in the tutorial.

For example, following here: https://github.com/MoseleyBioinformaticsLab/icikt/blob/6852b446d60794ba08c9d9ea234ec0e0e8747a81/README.rst?plain=1#L75

Should be a code block with some analysis:

```
import icikt
import numpy

exampleArray = numpy.random.randn(100, 2)

corr, pval, tmax = icikt.icikt(exampleArray[:, 0], exampleArray[:, 1])

scaled, corrRaw, pvals, tauMax = icikt.iciktArray(exampleArray)
```

This should be in the README, front page of the guide, and tutorial.

I would also bolster it with examples with a matrix as well.
I need to update some of the examples on https://moseleybioinformaticslab.github.io/ICIKendallTau/index.html too!
